version: '3'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: